server:
  port: 4001

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 1234567890123raam456789012345678901234567890nsdsi123456789012345678901234
  expiration: 3600000

logging:
  level:
    org.springframework.security: DEBUG